'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EditorPlus.UI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  // sample text に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InsertTextBox_Text() As String
            Get
                Return ResourceManager.GetString("InsertTextBox.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Insert to End に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InsertToEndButton_Content() As String
            Get
                Return ResourceManager.GetString("InsertToEndButton.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Insert to Head に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InsertToHeadButton_Content() As String
            Get
                Return ResourceManager.GetString("InsertToHeadButton.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Line End に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InsertToLineEndButton_Content() As String
            Get
                Return ResourceManager.GetString("InsertToLineEndButton.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Line Head に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property InsertToLineHeadButton_Content() As String
            Get
                Return ResourceManager.GetString("InsertToLineHeadButton.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  None に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NonePadding_Content() As String
            Get
                Return ResourceManager.GetString("NonePadding.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  None-padding に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NonePadding_ToolTip() As String
            Get
                Return ResourceManager.GetString("NonePadding.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Padding: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Padding_Text() As String
            Get
                Return ResourceManager.GetString("Padding.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Skip if started/ended with text に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SkipIfStartedOrEndWithTextCheckBox_Content() As String
            Get
                Return ResourceManager.GetString("SkipIfStartedOrEndWithTextCheckBox.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Skip if started/ended with text に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SkipIfStartedOrEndWithTextCheckBox_ToolTip() As String
            Get
                Return ResourceManager.GetString("SkipIfStartedOrEndWithTextCheckBox.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Space に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SpacePadding_Content() As String
            Get
                Return ResourceManager.GetString("SpacePadding.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Space-padding に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SpacePadding_ToolTip() As String
            Get
                Return ResourceManager.GetString("SpacePadding.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Start number: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StartNumber_Text() As String
            Get
                Return ResourceManager.GetString("StartNumber.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Zero に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ZeroPadding_Content() As String
            Get
                Return ResourceManager.GetString("ZeroPadding.Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Zero-padding に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ZeroPadding_ToolTip() As String
            Get
                Return ResourceManager.GetString("ZeroPadding.ToolTip", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
