//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Surviveplus.EditorPlus {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Surviveplus.EditorPlus.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Can not create tool window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Serial Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertSerialNumberCaption {
            get {
                return ResourceManager.GetString("InsertSerialNumberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertTextCaption {
            get {
                return ResourceManager.GetString("InsertTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activate text editor to format text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageActivateTextEditorForFormatText {
            get {
                return ResourceManager.GetString("MessageActivateTextEditorForFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activate text editor to insert text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageActivateTextEditorForInsertText {
            get {
                return ResourceManager.GetString("MessageActivateTextEditorForInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not open folder for the active file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCanNotOpenFolder {
            get {
                return ResourceManager.GetString("MessageCanNotOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input number to insert serial number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageInputNumber {
            get {
                return ResourceManager.GetString("MessageInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Folder for the Active File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenActiveFolderCaption {
            get {
                return ResourceManager.GetString("OpenActiveFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextFormatCaption {
            get {
                return ResourceManager.GetString("TextFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Tool Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
