//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Surviveplus.EditorPlus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Surviveplus.EditorPlus.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Serial Number.
        /// </summary>
        internal static string InsertSerialNumberCaption {
            get {
                return ResourceManager.GetString("InsertSerialNumberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text.
        /// </summary>
        internal static string InsertTextCaption {
            get {
                return ResourceManager.GetString("InsertTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate text editor to format text..
        /// </summary>
        internal static string MessageActivateTextEditorForFormatText {
            get {
                return ResourceManager.GetString("MessageActivateTextEditorForFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate text editor to insert text..
        /// </summary>
        internal static string MessageActivateTextEditorForInsertText {
            get {
                return ResourceManager.GetString("MessageActivateTextEditorForInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open folder for the active file..
        /// </summary>
        internal static string MessageCanNotOpenFolder {
            get {
                return ResourceManager.GetString("MessageCanNotOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input number to insert serial number..
        /// </summary>
        internal static string MessageInputNumber {
            get {
                return ResourceManager.GetString("MessageInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder for the Active File.
        /// </summary>
        internal static string OpenActiveFolderCaption {
            get {
                return ResourceManager.GetString("OpenActiveFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Text.
        /// </summary>
        internal static string TextFormatCaption {
            get {
                return ResourceManager.GetString("TextFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tool Window.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
