//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Surviveplus.EditorPlus.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Surviveplus.EditorPlus.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_Text {
            get {
                return ResourceManager.GetString("about.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip if started/ended with text.
        /// </summary>
        internal static string checkSkipStartOrEndWith_Content {
            get {
                return ResourceManager.GetString("checkSkipStartOrEndWith.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip if started/ended with text.
        /// </summary>
        internal static string checkSkipStartOrEndWith_ToolTip {
            get {
                return ResourceManager.GetString("checkSkipStartOrEndWith.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string formatButton_Content {
            get {
                return ResourceManager.GetString("formatButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Sample text - {0} - {1} - {2}.
        /// </summary>
        internal static string formatText_Text {
            get {
                return ResourceManager.GetString("formatText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // sample text.
        /// </summary>
        internal static string InsertTextBox_Text {
            get {
                return ResourceManager.GetString("InsertTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to End.
        /// </summary>
        internal static string InsertToEndButton_Content {
            get {
                return ResourceManager.GetString("InsertToEndButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to Head.
        /// </summary>
        internal static string InsertToHeadButton_Content {
            get {
                return ResourceManager.GetString("InsertToHeadButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NonePadding_Content {
            get {
                return ResourceManager.GetString("NonePadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None-padding.
        /// </summary>
        internal static string NonePadding_ToolTip {
            get {
                return ResourceManager.GetString("NonePadding.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding:.
        /// </summary>
        internal static string Padding_Text {
            get {
                return ResourceManager.GetString("Padding.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string SpacePadding_Content {
            get {
                return ResourceManager.GetString("SpacePadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space-padding.
        /// </summary>
        internal static string SpacePadding_ToolTip {
            get {
                return ResourceManager.GetString("SpacePadding.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start number:.
        /// </summary>
        internal static string StartNumber_Text {
            get {
                return ResourceManager.GetString("StartNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string ZeroPadding_Content {
            get {
                return ResourceManager.GetString("ZeroPadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero-padding.
        /// </summary>
        internal static string ZeroPadding_ToolTip {
            get {
                return ResourceManager.GetString("ZeroPadding.ToolTip", resourceCulture);
            }
        }
    }
}
