//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Surviveplus.EditorPlus.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Surviveplus.EditorPlus.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string about_Text {
            get {
                return ResourceManager.GetString("about.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip if started/ended with text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkSkipStartOrEndWith_Content {
            get {
                return ResourceManager.GetString("checkSkipStartOrEndWith.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip if started/ended with text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkSkipStartOrEndWith_ToolTip {
            get {
                return ResourceManager.GetString("checkSkipStartOrEndWith.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string formatButton_Content {
            get {
                return ResourceManager.GetString("formatButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // Sample text - {0} - {1} - {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string formatText_Text {
            get {
                return ResourceManager.GetString("formatText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // sample text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertTextBox_Text {
            get {
                return ResourceManager.GetString("InsertTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert to End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertToEndButton_Content {
            get {
                return ResourceManager.GetString("InsertToEndButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert to Head に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertToHeadButton_Content {
            get {
                return ResourceManager.GetString("InsertToHeadButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonePadding_Content {
            get {
                return ResourceManager.GetString("NonePadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None-padding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonePadding_ToolTip {
            get {
                return ResourceManager.GetString("NonePadding.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Padding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Padding_Text {
            get {
                return ResourceManager.GetString("Padding.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpacePadding_Content {
            get {
                return ResourceManager.GetString("SpacePadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space-padding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpacePadding_ToolTip {
            get {
                return ResourceManager.GetString("SpacePadding.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start number: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartNumber_Text {
            get {
                return ResourceManager.GetString("StartNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZeroPadding_Content {
            get {
                return ResourceManager.GetString("ZeroPadding.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero-padding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZeroPadding_ToolTip {
            get {
                return ResourceManager.GetString("ZeroPadding.ToolTip", resourceCulture);
            }
        }
    }
}
